services:
  - type: web
    name: helpdesk-mini
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run seed && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: helpdesk-db
          property: connectionString

databases:
  - name: helpdesk-db
    databaseName: helpdesk
    user: helpdesk_user
